### ISSUE TITLE
Unicode characters not show in dzen2-git

### ISSUE THREAD

**Issue by x0Bloot** [oxhak/archlinux-desktop-config-files#2]
Hi oxhak,

Some unicode characters none visible on panel1 and panel2 in dzen2-git.

Have you got a tips for that ?

**Comment by oxhak** [comment]
fonts missing, try install xorg fonts

> local/xorg-font-util 1.3.1-2 (xorg-fonts xorg)
>     X.Org font utilities
> local/xorg-fonts-alias 1.0.3-2
>     X.org font alias files
> local/xorg-fonts-encodings 1.0.4-5 (xorg-fonts xorg)
>     X.org font encoding files
> local/xorg-fonts-type1 7.7-2
>     X.org Type1 fonts
> local/xorg-mkfontscale 1.1.3-1 (xorg-apps xorg)
>     Create an index of scalable font files for X
> local/xorgproto 2018.4-1
>     combined X.Org X11 Protocol headers

**Comment by x0Bloot** [comment]
I've already this packages, which version of dzen do you used ?
I'm on this version 
local/dzen2 0.9.5git-6
    X notification utility

**Comment by oxhak** [comment]
font used in dzen2 is terminus-normal
try install terminus fonts packages
or change the font type in panel*.sh files
https://github.com/oxhak/archlinux-desktop-config-files/blob/0a9ad96202a8e5a27da9269f2e088f9d02173afd/.config/herbstluftwm/panel.sh#L6

**Comment by x0Bloot** [comment]
On line 34 [https://github.com/oxhak/archlinux-desktop-config-files/blob/0a9ad96202a8e5a27da9269f2e088f9d02173afd/.config/herbstluftwm/panel2.sh](url)
This arrow key won't show in dzen2, it appear with square character

Or in this file [https://github.com/oxhak/archlinux-desktop-config-files/blob/0a9ad96202a8e5a27da9269f2e088f9d02173afd/.conky/statusbar](url) line 36, arrow key characters

**Comment by oxhak** [comment]
I can see it correctly in my terminal, your missing package is in here, good luck

> local/artwiz-fonts 1.3-10
>     This is set of (improved) artwiz fonts
> local/cantarell-fonts 1:0.111-1
>     Humanist sans serif font
> local/fluidsynth 1.1.11-2
>     A real-time software synthesizer based on the SoundFont 2 specifications
> local/font-bh-ttf 1.0.3-4
>     X.org Luxi Truetype fonts
> local/font-bitstream-speedo 1.0.2-4
>     Bitstream Speedo fonts
> local/fontconfig 2:2.13.1+12+g5f5ec56-1
>     A library for configuring and customizing font access
> local/fontforge 20170731-2
>     Outline and bitmap font editor
> local/freetype2 2.9.1-1
>     Font rasterization library
> local/ftgl 2.1.3rc5-10
>     OpenGL library to use arbitrary fonts
> local/gnome-font-viewer 3.30.0-1 (gnome)
>     A font viewer utility for GNOME
> local/gsfonts 20180524-1
>     (URW)++ Core Font Set [Level 2]
> local/gtk2fontsel 0.1-6
>     Font selection and preview tool
> local/lib32-fontconfig 2:2.13.1+12+g5f5ec56-1
>     A library for configuring and customizing font access (32-bit)
> local/lib32-freetype2 2.9.1-1
>     TrueType font rendering library (32-bit)
> local/lib32-libxft 2.3.2-2
>     FreeType-based font drawing library for X (32-bit)
> local/lib32-sdl2_ttf 2.0.14-2
>     Library that allows you to use TrueType fonts in your SDL applications (Version 2) (32-bit)
> local/lib32-sdl_ttf 2.0.11-4
>     A library that allows you to use TrueType fonts in your SDL applications (32-bit)
> local/libfontenc 1.1.3-2
>     X11 font encoding library
> local/libxfont2 2.0.3-1
>     X11 font rasterisation library
> local/libxft 2.3.2-2
>     FreeType-based font drawing library for X
> local/noto-fonts 20180322-1
>     Google Noto TTF fonts
> local/noto-fonts-emoji 20180810-1
>     Google Noto emoji fonts
> local/pangox-compat 0.0.2+2+gedb9e09-2
>     X Window System font support for Pango
> local/powerline-fonts-git r189.d983af4-1
>     Powerline fonts for X11 and the console
> local/sdl2_ttf 2.0.14-1
>     A library that allows you to use TrueType fonts in your SDL applications (Version 2)
> local/sdl_ttf 2.0.11-4
>     A library that allows you to use TrueType fonts in your SDL applications
> local/t1lib 5.1.2-6
>     Library for generating character- and string-glyphs from Adobe Type 1 fonts
> local/ttf-anonymous-pro 1.003-3
>     A family of four fixed-width fonts designed especially with coding in mind
> local/ttf-bitstream-vera 1.10-11
>     Bitstream Vera fonts.
> local/ttf-cheapskate 2.0-12
>     TTFonts collection from dustimo.com
> local/ttf-dejavu 2.37-2
>     Font family based on the Bitstream Vera Fonts with a wider range of characters
> local/ttf-freefont 20120503-5
>     Set of free outline fonts covering the Unicode character set
> local/ttf-latex-xft-fonts 0.1-1
>     LaTeX ttf fonts needed by Abiword to display formulas
> local/ttf-liberation 2.00.1-7
>     Red Hats Liberation fonts.
> local/ttf-mac-fonts 20100901.134-1
>     Mac fonts including Lucida Grande, Apple Garamond and other fonts from Apple
> local/ttf-ms-fonts 2.0-10
>     Core TTF Fonts from Microsoft
> local/ttf-symbola 11.00-3
>     Font for unicode symbols (part of Unicode Fonts for Ancient Scripts).
> local/ttf-ubuntu-font-family 0.83-3
>     Ubuntu font family
> local/ttf-vlgothic 20141206-2
>     Japanese TrueType fonts from Vine Linux
> local/woff2 1.0.2-1
>     Web Open Font Format 2 reference implementation
> local/xorg-bdftopcf 1.1-1 (xorg xorg-apps)
>     Convert X font from Bitmap Distribution Format to Portable Compiled Format
> local/xorg-font-util 1.3.1-2 (xorg-fonts xorg)
>     X.Org font utilities
> local/xorg-font-utils 7.6-5
>     Transitional package depending on xorg font utilities
> local/xorg-fonts-alias 1.0.3-2
>     X.org font alias files
> local/xorg-fonts-encodings 1.0.4-5 (xorg-fonts xorg)
>     X.org font encoding files
> local/xorg-fonts-type1 7.7-2
>     X.org Type1 fonts
> local/xorg-mkfontdir 1.0.7-9 (xorg xorg-apps)
>     Create an index of X font files in a directory
> local/xorg-mkfontscale 1.1.3-1 (xorg-apps xorg)
>     Create an index of scalable font files for X
> local/xorgproto 2018.4-1
>     combined X.Org X11 Protocol headers

**Comment by oxhak** [comment]
maybe related to theses packages

> local/libfontenc 1.1.3-2
> X11 font encoding library
> local/libxfont2 2.0.3-1
> X11 font rasterisation library
> local/libxft 2.3.2-2
> FreeType-based font drawing library for X

**Comment by x0Bloot** [comment]
Thanks for, the list of font packages.
I will test this.

Can you confirm your version of dzen2 ? I see on website on issue to downgrade of version dzen2-git to version 0.8.5.

Thanks in advance

**Comment by oxhak** [comment]
local/dzen2 0.9.5.14.488ab66-1
    General purpose messaging, notification and menuing program for X11

**Comment by x0Bloot** [comment]
Thanks for your support, i have found another issue.
